name: Desktop Reusable Release Workflow

on:
  push:
  workflow_call:
    inputs:
      channel:
        required: true
        type: string

jobs:
  Mac:
    if: false
    runs-on: macos-latest
    env:
      CSC_LINK: ${{ secrets.MAC_CI_KEYS }}
      CSC_KEY_PASSWORD: ${{ secrets.MAC_CI_KEYS_PASSWORD }}
      NOTARIZE_APPLE_ID: ${{ secrets.NOTARIZE_APPLE_ID }}
      NOTARIZE_APPLE_ID_PASSWORD: ${{ secrets.NOTARIZE_APPLE_ID_PASSWORD }}
      DEFAULT_SYNC_SERVER: ${{ secrets.DEFAULT_SYNC_SERVER }}
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: find ./../ -name "*.ts" -not -path "*node_modules*" -exec sed -i -r "s;DEFAULT_SYNC_SERVER;'${{ secrets.DEFAULT_SYNC_SERVER }}';g" {} \;
      - run: yarn install --immutable
      - run: yarn build:desktop
      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV
      - run: echo DEFAULT_SYNC_SERVER=${{ secrets.DEFAULT_SYNC_SERVER }} >> .env
      - run: cat .env

      - name: Compile Mac
        run: yarn run webpack --config desktop.webpack.prod.js --env .env
      - name: MacX64
        run: |
          yarn run electron-builder --mac --x64 --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
          node scripts/fixMacZip.js ${{ env.APP_VERSION }}
      - name: MacArm64
        run: yarn run electron-builder --mac --arm64 --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: dmg
          path: packages/desktop/dist/*.dmg

  Linux:
    runs-on: ubuntu-latest
    env:
      DEFAULT_SYNC_SERVER: ${{ secrets.DEFAULT_SYNC_SERVER }}
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: find ./../ -name "*.ts" -not -path "*node_modules*" -exec sed -i -r "s;DEFAULT_SYNC_SERVER;'${{ secrets.DEFAULT_SYNC_SERVER }}';g" {} \;

      - run: yarn install --immutable

      - name: Replace markdown-hybrid with my updated version
        run: |
          rm -rf ./../../node_modules/@standardnotes/markdown-hybrid/
          git clone https://github.com/kmantel/markdown-pro.git ./../../node_modules/@standardnotes/markdown-hybrid

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV
      - run: echo DEFAULT_SYNC_SERVER=${{ secrets.DEFAULT_SYNC_SERVER }} >> .env
      - run: cat .env

      - name: Compile for AppImage
        run: yarn run webpack --config desktop.webpack.prod.js --env .env
      # - name: AppImage
      #   run: yarn run electron-builder --linux --x64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      - name: AppImageX64
        run: yarn run electron-builder --linux --x64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      # - name: AppImageArm64
      #   run: yarn run electron-builder --linux --arm64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Deb
        run: |
          yarn run webpack --config desktop.webpack.prod.js --env deb --env .env
          yarn run electron-builder --linux --x64 -c.linux.target=deb --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      # - name: DebArm64
      #   env:
      #     npm_config_target_arch: 'arm64'
      #     USE_SYSTEM_FPM: 'true'
      #   run: |
      #     yarn run webpack --config desktop.webpack.prod.js --env deb --env .env
      #     yarn run electron-builder --linux --arm64 -c.linux.target=deb --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      # - name: Dir
      #   run: |
      #     yarn run webpack --config desktop.webpack.prod.js --env .env
      #     yarn run electron-builder --linux --x64 -c.linux.target=dir --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      # - name: DirArm64
      #   run: |
      #     yarn run webpack --config desktop.webpack.prod.js --env .env
      #     yarn run electron-builder --linux --arm64 -c.linux.target=dir --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}
      #   env:
      #     npm_config_target_arch: 'arm64'

      # - name: Snap
      #   run: |
      #     sudo snap install snapcraft --classic
      #     yarn run webpack --config desktop.webpack.prod.js --env snap --env .env
      #     yarn run electron-builder --linux --x64 -c.linux.target=snap --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: appimage
          path: packages/desktop/dist/*.AppImage

      - name: UploadDeb
        uses: actions/upload-artifact@v3.0.0
        with:
          name: deb
          path: packages/desktop/dist/*.deb

  WindowsOnLinux:
    runs-on: ubuntu-latest
    env:
      DEFAULT_SYNC_SERVER: ${{ secrets.DEFAULT_SYNC_SERVER }}
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: find ./../ -name "*.ts" -not -path "*node_modules*" -exec sed -i -r "s;DEFAULT_SYNC_SERVER;'${{ secrets.DEFAULT_SYNC_SERVER }}';g" {} \;

      - run: yarn install --immutable

      - name: Replace markdown-hybrid with my updated version
        run: |
          rm -rf ./../../node_modules/@standardnotes/markdown-hybrid/
          git clone https://github.com/kmantel/markdown-pro.git ./../../node_modules/@standardnotes/markdown-hybrid

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV
      - run: echo DEFAULT_SYNC_SERVER=${{ secrets.DEFAULT_SYNC_SERVER }} >> .env
      - run: cat .env

      - run: sudo dpkg --add-architecture i386
      - run: wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
      - run: sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
      - run: sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
      - run: sudo apt install --install-recommends winehq-stable

      - run: yarn run webpack --config desktop.webpack.prod.js --env .env
      - run: yarn run electron-builder --windows --x64 --ia32 --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Upload win-unpacked
        if: always()
        uses: actions/upload-artifact@v3.0.0
        with:
          name: win-unpacked
          path: packages/desktop/dist/win-unpacked

      - name: Upload x64 exe
        if: always()
        uses: actions/upload-artifact@v3.0.0
        with:
          name: exe
          path: packages/desktop/dist/*x64.exe

  Windows:
    if: false
    runs-on: windows-latest
    env:
      WINDOWS_TOKEN_ALIAS: ${{ secrets.WINDOWS_TOKEN_ALIAS }}
      WINDOWS_TOKEN_PASSWORD: ${{ secrets.WINDOWS_TOKEN_PASSWORD }}
      DEFAULT_SYNC_SERVER: ${{ secrets.DEFAULT_SYNC_SERVER }}
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - run: find ./../ -name "*.ts" -not -path "*node_modules*" -exec sed -i -r "s;DEFAULT_SYNC_SERVER;'${{ secrets.DEFAULT_SYNC_SERVER }}';g" {} \;
      - run: echo DEFAULT_SYNC_SERVER=${{ secrets.DEFAULT_SYNC_SERVER }} >> .env
      - run: cat .env
      - run: yarn install --immutable
      - run: yarn build:desktop
      - run: yarn run webpack --config desktop.webpack.prod.js --env .env
      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $env:GITHUB_ENV
      - run: yarn run electron-builder --windows --x64 --ia32 --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Upload win-unpacked
        if: always()
        uses: actions/upload-artifact@v3.0.0
        with:
          name: win-unpacked-win
          path: packages/desktop/dist/win-unpacked

      - name: Upload x64 exe
        if: always()
        uses: actions/upload-artifact@v3.0.0
        with:
          name: exe-win
          path: packages/desktop/dist/*x64.exe
